export const ROUTE_NAMES = {
  HOME: 'Home',
  AUTH_STACK: 'AuthStack',
  DASHBOARD_STACK: 'DashboardStack',
  SPLASH: 'SplashScreen',
  LOGIN: 'LoginScreen',
  VERIFY_OTP_SCREEN: 'VerifyOTPScreen',
  DASHBOARD_SCREEN: 'DashboardScreen',
  ADD_DONAR_SCREEN: 'AddDonarScreen',
  EVENTS_SCREEN: 'EventsScreen',
  ADD_EVENT_SCREEN: 'AddEventScreen',
  DONATION_STACK: 'DonationStack',
  DONATION_SCREEN: 'DonationScreen',
  ADD_DONATION_SCREEN: 'AddDonations',
  PROFILE_STACK: 'ProfileStack',
  PROFILE_SCREEN: 'ProfileScreen',
  USER_SCREEN: 'UserScreen',
  ADD_USER_SCREEN: 'AddUserScreen',
  UPDATE_PROFILE_SCREEN: 'UpdateProfileScreen',
  RELATION_SCREEN: 'ViewRelationshipItem',
  OCCASION_SCREEN: 'ViewOccasionItem',
  USER_DONATION_SCREEN: 'DonationItem',
  PRIVACY_POLICY_SCREEN: 'PrivacyPolicy',
  DONOR_DETAIL_SCREEN: 'DonorDetails',
  DONOR_OCCASION_SCREEN: 'DonorOccasions',
  DONOR_RELATION_SCREEN: 'DonorRelations',
  DONOR_DONATION_SCREEN: 'DonorDonations',
  DONATION_DETAIL_SCREEN: 'DonationDetail',
  EVENT_DETAIL_SCREEN: 'EventDetail',
  CATEGORIES_SCREEN: 'CategoriesScreen',
  ADD_CATEGORY_SCREEN: 'AddCategoryScreen',
  REPORT_SCREEN: 'ReportScreen',
};

export const PREFERENCE = {
  USER_ID: 'user_id',
  JWT_TOKEN: 'jwt_token',
  IS_LOGGED_IN: 'is_logged_in',
  USER: 'user',
};

export const BASE_URL = 'https://test.vidyaranyam.in';

export const DEFAULT_DATE = '1111-11-11';


export const chartsColors = [
  '#FF5733',
  '#33FF57',
  '#3357FF',
  '#FF33A6',
  '#33FFA6',
  '#A633FF',
  '#FFD733',
  '#33D7FF',
  '#FF3333',
  '#33FF33',
  '#3333FF',
  '#FF5733',
  '#FF8C33',
  '#FFC233',
  '#FFF333',
  '#D7FF33',
  '#A6FF33',
  '#57FF33',
  '#33FF8C',
  '#33FFC2',
  '#33FFF3',
  '#33D7FF',
  '#33A6FF',
  '#3357FF',
  '#5733FF',
  '#8C33FF',
  '#C233FF',
  '#F333FF',
  '#FF33D7',
  '#FF33A6',
  '#FF338C',
  '#FF3357',
  '#FF3357',
  '#FF33FF',
  '#FF33C2',
  '#FF33A6',
  '#FF338C',
  '#FF3333',
  '#FF5733',
  '#FF8C33',
]