export const URLS = {
  LOGIN: `/api/login`,
  VERIFY_OTP: `/api/verify-otp`,
  GOOGLE_LOGIN: '/api/googleLogin',
  USERS: '/api/users',
  CHECK_EMAIL: '/api/email-exists',
  EVENTS: '/api/events',
  DONATIONS: '/api/donations',
  CATEGORIES: '/api/categories',
  ONLINE_PAYMENT: '/api/payments/newpayment',
  DONATION_CATEGORIES: '/api/category-donations',
  DONATION_GET_DATA: '/api/get-data',
  DASHBOARD_TOTAL_DONATION: '/api/dashboard/totaldonation',
  DASHBOARD_DONATION_BY_EVENTS: '/api/dashboard/donationsbyevents',
  DASHBOARD_DONATION_BY_DATE: '/api/dashboard/donationsbydate',
  DASHBOARD_TOP_TEN_DONORS: '/api/dashboard/top10donors',
  DASHBOARD_BIRTHDAY_ANNIVERSARY: '/api/dashboard/bdaysannivs',
  DASHBOARD_UPCOMING_EVENTS: '/api/dashboard/events',
  DASHBOARD_RECURRING_DONATION: '/api/dashboard/recurringdonorsdonations',
  DASHBOARD_JEEVANADI_NUMBERS: '/api/dashboard/jeevanadinumbers',
  CHANGE_STATUS: '/api/change-status',
  CHANGE_CATEGORY_STATUS: '/api/change-status-cat',
  CHANGE_EVENT_STATUS: '/api/change-status-seva',
  GET_REPORT: '/api/reports',
};
